
version: "3.8"
services:
  my_portfolio:
    build: .
    ports:
      - "81:80"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}